model:
  input_len: 96
  hidden_channels: 384
  num_layers: 5

optim:
  batch_size: 64
  lr: 0.0006
  epochs: 50
  es_patience: 5
  scheduler:
    name: ReduceLROnPlateau
    patience: 4
    step_size: 5000
    decay_factor: 0.5