model:
  num_layers: 2
  hidden_channels: 512
  sg_emb_size: 128
  lat_hidden_channels: 64
  lat_num_layers: 1
  comp_num_layers: 1
  comp_hidden_channels: 64
  comp_phys_embeds:
    use: True
    z_emb_size: 32
    period_emb_size: 16
    group_emb_size: 16
    properties_proj_size: 32
    n_elements: 90

optim:
  batch_size: 32
  lr: 0.001
  epochs: 10
  es_patience: 3
