  frame_averaging: "" # {"2D", "3D", "DA", ""}
  fa_method: "" # {"", all, stochastic, det, se3-all, se3-stochastic, se3-det}
  return_pyxtal: True 
  model:
    regress_forces: direct
    hidden_channels: 256
    num_filters: 480
    num_interactions: 5
    num_gaussians: 136
    preprocess: pbc_preprocess
    tag_hidden_channels: 0  # only for OC20
    pg_hidden_channels: 0  # period & group embedding hidden channels
    phys_embeds: False  # physics-aware embeddings for atoms
    phys_hidden_channels: 0
    energy_head: "weighted-av-final-embeds"  # Energy head: {False, weighted-av-initial-embeds, weighted-av-final-embeds}
    skip_co: False  # Skip connections {False, "add", "concat"}
    second_layer_MLP: False  # in EmbeddingBlock
    complex_mp: True  # 2-layer MLP in Interaction blocks
    mp_type: updownscale_base  # Message Passing type {'base', 'simple', 'updownscale', 'updownscale_base'}
    graph_norm: True  # graph normalization layer
    force_decoder_type: "mlp" # force head (`"simple"`, `"mlp"`, `"res"`, `"res_updown"`)
    force_decoder_model_config:
      simple:
        hidden_channels: 128
        norm: batch1d # batch1d, layer or null
      mlp:
        hidden_channels: 256
        norm: batch1d # batch1d, layer or null
      res:
        hidden_channels: 128
        norm: batch1d # batch1d, layer or null
      res_updown:
        hidden_channels: 128
        norm: batch1d # batch1d, layer or null
  optim:
    batch_size: 4
    lr: 0.0012
    epochs: 20
    es_patience: 7
    num_workers: 4
    energy_grad_coefficient: 10
    force_coefficient: 30
    energy_coefficient: 1
    scheduler:
      name: ReduceLROnPlateau
      decay_factor: 0.5
      patience: 5