entity: mila-ocp
project: Dave-MBform
program: run.py
method: bayes
metric:
  goal: minimize
  name: val_mae

parameters:
  model.hidden_channels:
    values: [64, 128, 192, 256, 320, 384, 448, 512, 576]
  model.num_layers:
    values: [2, 3, 4, 5]
  model.sg_emb_size:
    values: [64, 128, 196, 256]
  model.lat_hidden_channels:
    values: [64, 128, 192, 256, 320, 384, 448]
  model.lat_num_layers:
    values: [1, 2, 3]
  model.comp_num_layers:
    values: [1, 2, 3]
  model.comp_hidden_channels:
    values: [32, 64, 128, 196]
  model.comp_phys_embeds.z_emb_size:
    values: [16, 32, 64, 128]
  model.comp_phys_embeds.period_emb_size:
    values: [8, 16, 32, 64, 128, 256]
  model.comp_phys_embeds.group_emb_size:
    values: [8, 16, 32, 64, 128, 256]
  model.comp_phys_embeds.properties_proj_size:
    values: [16, 32, 64, 128]

  optim.batch_size:
    values: [64, 128, 192, 256, 320, 384, 448]
  optim.es_patience:
    values: [3, 5, 7, 9, 11]
  optim.lr:
    distribution: log_uniform_values
    min: 0.0002
    max: 0.002
  optim.epochs:
    values: [100]
  optim.scheduler.name:
    values: ["ReduceLROnPlateau"]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "physmlp-mbform"
  - "--wandb_entity=mila-ocp"
  - "--wandb_project=Dave-MBform"
  - ${args}
