entity: mila-ocp
project: Dave-MP20
program: run.py
method: bayes
metric:
  goal: minimize
  name: total_val_mae

parameters:
  model.hidden_channels:
    values: [64, 128, 196, 256, 320, 384]
  model.num_layers:
    values: [2, 3, 4, 5, 6]
  model.sg_emb_size:
    values: [64, 128, 196, 256]
  model.lat_hidden_channels:
    values: [32, 64, 128, 196]
  model.lat_num_layers:
    values: [1, 2, 3, 4]
  model.comp_num_layers:
    values: [1, 2, 3, 4]
  model.comp_hidden_channels:
    values: [32, 64, 128, 196, 256]
  model.comp_phys_embeds.z_emb_size:
    values: [16, 32, 64, 128]
  model.comp_phys_embeds.period_emb_size:
    values: [8, 16, 32, 64]
  model.comp_phys_embeds.group_emb_size:
    values: [8, 16, 32, 64]
  model.comp_phys_embeds.properties_proj_size:
    values: [16, 32, 64, 128, 256]
  optim.batch_size:
    values: [32, 64, 128, 196, 256]
  optim.lr:
    distribution: log_uniform_values
    min: 0.00002
    max: 0.002
  optim.epochs:
    values: [100]

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--config"
  - "physmlp-mbform"
  - ${args}
