src: $root/nrcc_ionic_conductivity
crossval: 3
target: Ionic conductivity (S cm-1)
scales:
  x:
    load: torch
    mean: $src/x.mean
    std: $src/x.std
  y: False
comp_size: 83
lat_size: 6
alphabet: [
  1,
  3,
  5,
  6,
  7,
  8,
  9,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  29,
  30,
  31,
  32,
  34,
  35,
  38,
  39,
  40,
  41,
  42,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  56,
  57,
  58,
  59,
  60,
  62,
  64,
  68,
  71,
  72,
  73,
  74,
  82
] 