# more epochs, larger batch size, explore faenet: larger model & skip-co & mlp_rij
job:
  mem: 24GB
  cpus: 4
  gres: gpu:1
  time: 30:00
  partition: main

default:
  model_config:
    batch_size: 64

runs:
  - model_config:
      lr: 0.0001
  - model_config:
      lr: 0.0005
