job:
  mem: 32GB
  cpus: 4
  gres: gpu:rtx8000:1
  partition: long

default: 
  wandb_tags: "baselines"

runs:
  - config: graph-mp20
    wandb_note: "Graph baseline"
  - config: mlp-mp20
    wandb_note: "MLP baseline"
  - config: physmlp-mp20
    wandb_note: "PhysMLP baseline"